services:

  app:
    build: ./app
    container_name: front-end 
    volumes: ['./app/src:/appcode']
      #    restart: unless-stopped
    ports:
      - 8501:8501

  api:
    build: ./api
    container_name: web-api
    hostname: web-api
    volumes: ['./api:/apicode']
      
    ports:
      - 4000:4000

  db:
    env_file:
      - ./api/.env
    image: mysql:8
    container_name: mysql_db
    volumes:
      - ./database-files:/docker-entrypoint-initdb.d/:ro

    ports:
      - 3200:3306

    restart: unless-stopped


